name:                bytestring-encoding
version:             0.1.2.0
github:              "msakai/bytestring-encoding"
license:             BSD3
author:              "Masahiro Sakai"
maintainer:          "masahiro.sakai@gmail.com"
copyright:           "2018 Masahiro Sakai"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            ByteString ↔ Text converter based on GHC.IO.Encoding
category:            Data, Text

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/msakai/bytestring-encoding#readme>

tested-with: 'GHC==7.10.3 GHC==8.0.2 GHC==8.2.2 GHC==8.4.4 GHC==8.6.5 GHC==8.8.4 GHC==8.10.7 GHC==9.0.2 GHC==9.2.8 GHC==9.4.5'

dependencies:
- base >=4.8 && <5
- bytestring >=0.10.6.0 && <0.13
- text >=1.2.2.2 && <2.2

library:
  source-dirs: src

tests:
  bytestring-encoding-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytestring-encoding
    - QuickCheck
    - tasty >=0.10.1
    - tasty-hunit
    - tasty-quickcheck
    - tasty-th
    - deepseq
