on: [push, pull_request]
name: build
jobs:
  bytestring-encoding:
    name: bytestring-encoding
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ghc: '7.10.3'
            resolver: 'lts-6.35'
            os: ubuntu-20.04
            flags: ''
          - ghc: '8.0.2'
            resolver: 'lts-9.21'
            os: ubuntu-latest
            flags: ''
          - ghc: '8.2.2'
            resolver: 'lts-11.22'
            os: ubuntu-latest
            flags: ''
          - ghc: '8.4.4'
            resolver: 'lts-12.26'
            os: ubuntu-latest
            flags: ''
          - ghc: '8.6.5'
            resolver: 'lts-14.27'
            os: ubuntu-latest
            flags: ''
          - ghc: '8.8.4'
            resolver: 'lts-16.31'
            os: ubuntu-latest
            flags: ''
          - ghc: '8.10.7'
            resolver: 'lts-18.23'
            os: ubuntu-latest
            flags: ''
          - ghc: '9.0.2'
            resolver: 'lts-19.33'
            os: ubuntu-latest
            flags: ''
          - ghc: '9.2.8'
            resolver: 'lts-20.25'
            os: ubuntu-latest
          - ghc: '9.4.8'
            resolver: 'lts-21.25'
            os: ubuntu-latest
            flags: ''
          - ghc: '9.6.6'
            resolver: 'lts-22.43'
            os: ubuntu-latest
            coveralls: true
            flags: '--coverage'
          - ghc: '9.6.6'
            resolver: 'lts-22.43'
            os: windows-latest
            flags: ''
          - ghc: '9.6.6'
            resolver: 'lts-22.43'
            os: macos-latest
            flags: ''
          - ghc: '9.8.4'
            resolver: 'lts-23.11'
            os: ubuntu-latest
            flags: ''
          - ghc: '9.10.1'
            resolver: 'nightly-2025-03-05'
            os: ubuntu-latest
            flags: ''
    steps:
      - uses: actions/checkout@v4

      - uses: haskell-actions/setup@v2
        name: Setup Haskell
        with:
          ghc-version: ${{ matrix.ghc }}
          enable-stack: true
          stack-version: 'latest'
          stack-no-global: true
          stack-setup-ghc: true

      - uses: actions/cache@v4
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack

      # https://github.com/commercialhaskell/stack/issues/5405
      - name: Clear setup-exe-cache directory
        if: runner.os == 'macOS'
        continue-on-error: true
        run: rm -r ~/.stack/setup-exe-cache

      - name: Build
        shell: bash
        run: |
          echo "resolver: ${{ matrix.resolver }}" > stack.yaml
          stack build --test --no-run-tests --bench --no-run-benchmarks ${{ matrix.flags }}

      - name: Test
        run: stack test ${{ matrix.flags }}

      - name: Coveralls
        if: matrix.coveralls
        continue-on-error: true
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.7.0/shc-Linux-X64.tar.bz2 | tar -xj
          ./shc --repo-token="$COVERALLS_REPO_TOKEN" bytestring-encoding bytestring-encoding-test
